name: Test
on: ["push", "pull_request"]

jobs:
  ci:
    name: Run Test Suite
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go: ["1.22.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - run: "go test -v ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ matrix.go }}
          working-directory: ${{ matrix.dir }}

